application:
  info:
    app:
      name: '@project.artifactId@'
      version: '@project.version@'
      description: '@project.description@'

logging:
  pattern:
    console: '%d %-5level %logger : %msg%n'
  level:
    org.springframework: INFO
    org.springframework.boot.autoconfigure: ERROR
    org.hibernate.SQL: DEBUG
    shagui.rws.security: DEBUG

spring:
  application:
    name: '@project.artifactId@'
  banner:
    location: classpath:/banner/spring-boot-banner.txt
  output:
    ansi:
      enabled: ALWAYS
  sql:
    init:
      mode: embedded

rest:
  security:
    api-matcher:
      - /api/**
      - /v3/api-docs/**
      - /webjars/**
    cors:
      allowed-origins: '*'
      allowed-headers: '*'
      allowed-methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      max-age: 3600

management:
  endpoints:
    jmx:
      exposure:
        include: health,info,metrics,prometheus
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    # promoetheus:
    #   show-details: always
    shutdown:
      access: none

feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 10000
        loggerLevel: basic
